---
title: "ISU_DEP_EDU_DATA"
author: "Sam Shifflett"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##SOURCES:
MAKE SURE TO PUT ANY SOURCES YOU GUYS LOOK AT IN HERE!!!!
__________________________
-SAM
https://www.tutorialspoint.com/r/r_functions.htm
https://www.rdocumentation.org/packages/stringr/versions/1.4.0/topics/str_detect
https://stackoverflow.com/questions/17499013/how-do-i-make-a-list-of-data-frames
https://www.rdocumentation.org/packages/base/versions/3.5.3/topics/paste
#row names to column
https://stackoverflow.com/questions/29511215/convert-row-names-into-first-column
#transpose dataframe
http://www.rpubs.com/Mentors_Ubiqum/Transpose_Dataframe

-
-LIM

-
-DANNY

-

__________________________

PREPARE THE DATA
```{r}
devtools::install_github("Rdatatable/data.table", build_vignettes = FALSE)
library(httr)
library(jsonlite)
library(tidyverse)
library(plyr)
library(data.table)
options(scipen = 999)
#This is the URL for ISU data
url = "https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=KYthZktaAwB5CMGp9Keyl3raXpb6CS43CaMhbLkr&school.name=Iowa%20State%20University"
#This is the URL for UniIowa data
UIowaURL = "https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=KYthZktaAwB5CMGp9Keyl3raXpb6CS43CaMhbLkr&school.name=University%20of%20Iowa"
data_get<- GET(url)
data_get2 <- GET(UIowaURL)
get2json<- content(data_get, as = "parsed")
get2json2 <- content(data_get2, as = "parsed")
#----------------------------
#This function parses the Json repsonse into a dataframe for each category that we are analyzing
get_subs <- function(name) {
  completion = unlist(fromJSON(toJSON(name$completion,flatten=TRUE)))
  students = unlist(fromJSON(toJSON(name$student,flatten=TRUE)))
  admissions = unlist(fromJSON(toJSON(name$admissions,flatten=TRUE)))
  academics = unlist(fromJSON(toJSON(name$academics,flatten=TRUE)))
  aid = unlist(fromJSON(toJSON(name$aid,flatten=TRUE)))
  repayment = unlist(fromJSON(toJSON(name$repayment,flatten=TRUE)))
  earnings = unlist(fromJSON(toJSON(name$earnings,flatten=TRUE)))
  cost = unlist(fromJSON(toJSON(name$cost,flatten=TRUE)))
  completion = data.frame(completion)
  students = data.frame(students)
  admissions = data.frame(admissions)
  academics = data.frame(academics)
  aid = data.frame(aid)
  repayment= data.frame(repayment)
  earnings= data.frame(earnings)
  cost= data.frame(cost)
  yearList = c(list(completion),list(students),list(admissions),list(academics),list(aid),list(repayment),list(earnings),list(cost))
  add_col_name(yearList)
  return(change_zeros(yearList))
}

#creates a column in the first column for selecting
add_col_name <- function(data) {
  for(i in seq(from=1,to=length(data))) {
    if(dim(data[[i]]) != 0) {
      setDT(data[[i]], keep.rownames = TRUE)[]
    }
  }
}

#creates a new dataframe for dataframes with no repsonse from get_subs
change_zeros <- function(collect) {
  datalist = c()
  for(i in seq(from=1,to=length(collect),by=1)) {
    if(ncol(collect[[i]]) == 0) {
      data = data.frame(rn=c("avg_net_price.overall","students_with_pell_grant","sat_scores.average.overall","program_percentage.education","pell_grant_rate","repayment_cohort.3_year_declining_balance","6_yrs_after_entry.working_not_enrolled.income.lowest_tercile","avg_net_price.public"),empty="None")
      datalist = c(datalist,list(data))
    }
    else {
      datalist = c(datalist,list(collect[[i]]))
    }
  }
  return(datalist)
}

#grabs the ISU data associated with a certain subtopic and puts them into a list for each year
ISUlist_topics <- function(number) {
  tempList = list(ISUdata1997[[number]],ISUdata1998[[number]],ISUdata1999[[number]],ISUdata2000[[number]],ISUdata2001[[number]],ISUdata2002[[number]],ISUdata2003[[number]],ISUdata2004[[number]],ISUdata2005[[number]],ISUdata2006[[number]],ISUdata2007[[number]],ISUdata2008[[number]],ISUdata2009[[number]],ISUdata2010[[number]],ISUdata2011[[number]],ISUdata2012[[number]])
  return(rev(tempList))
}

#grabs the UI data associated with a certain subtopic and puts them into a list for each year
UIlist_topics <- function(number) {
  tempList = list(UIdata1997[[number]],UIdata1998[[number]],UIdata1999[[number]],UIdata2000[[number]],UIdata2001[[number]],UIdata2002[[number]],UIdata2003[[number]],UIdata2004[[number]],UIdata2005[[number]],UIdata2006[[number]],UIdata2007[[number]],UIdata2008[[number]],UIdata2009[[number]],UIdata2010[[number]],UIdata2011[[number]],UIdata2012[[number]])
  return(rev(tempList))
}

#joins all of the dataframes for each subtopic for ISU data
ISUjoin_rename <- function(number) {
  namesData = c("1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","stat")
  data = join_all(ISUlist_topics(number), by='rn', type='left')
  names(data) = rev(namesData)
  t_data = as.data.frame(t(as.matrix(data)))
  DF = t_data[2:nrow(t_data),1:ncol(t_data)]
  colnames(DF) = data[,1]
  for(i in seq(from=1,to=ncol(DF),by=1)) {
    names(DF)[i] = data[,1][i]
  }
  setDT(DF, keep.rownames = TRUE)[]
  return(DF)
}

#joins all of the dataframes for each subtopic for UI data
UIjoin_rename <- function(number) {
  namesData = c("1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","stat")
  data = join_all(UIlist_topics(number), by='rn', type='left')
  names(data) = rev(namesData)
  t_data = as.data.frame(t(as.matrix(data)))
  DF = t_data[2:nrow(t_data),1:ncol(t_data)]
  colnames(DF) = data[,1]
  for(i in seq(from=1,to=ncol(DF),by=1)) {
    names(DF)[i] = data[,1][i]
  }
  setDT(DF, keep.rownames = TRUE)[]
  return(DF)
}

#create dataframes for each sub category for each year
ISUdata2012 = get_subs(get2json$results[[1]]$`2012`)
ISUdata2011 = get_subs(get2json$results[[1]]$`2011`)
ISUdata2010 = get_subs(get2json$results[[1]]$`2010`)
ISUdata2009 = get_subs(get2json$results[[1]]$`2009`)
ISUdata2008 = get_subs(get2json$results[[1]]$`2008`)
ISUdata2007 = get_subs(get2json$results[[1]]$`2007`)
ISUdata2006 = get_subs(get2json$results[[1]]$`2006`)
ISUdata2005 = get_subs(get2json$results[[1]]$`2005`)
ISUdata2004 = get_subs(get2json$results[[1]]$`2004`)
ISUdata2003 = get_subs(get2json$results[[1]]$`2003`)
ISUdata2002 = get_subs(get2json$results[[1]]$`2002`)
ISUdata2001 = get_subs(get2json$results[[1]]$`2001`)
ISUdata2000 = get_subs(get2json$results[[1]]$`2000`)
ISUdata1999 = get_subs(get2json$results[[1]]$`1999`)
ISUdata1998 = get_subs(get2json$results[[1]]$`1998`)
ISUdata1997 = get_subs(get2json$results[[1]]$`1997`)
ISUdata1996 = get_subs(get2json$results[[1]]$`1996`)
#join all of the dataframes from each year into one full dataframe by subtopic
ISUcompletionData = ISUjoin_rename(1)
ISUstudentsData = ISUjoin_rename(2)
ISUadmissionData = ISUjoin_rename(3)
ISUacademicsData = ISUjoin_rename(4)
ISUaidData = ISUjoin_rename(5)
ISUrepaymentData = ISUjoin_rename(6)
ISUearningsData = ISUjoin_rename(7)
ISUcostData <- ISUjoin_rename(8)

#create dataframes for each sub category for each year
UIdata2012 = get_subs(get2json2$results[[1]]$`2012`)
UIdata2011 = get_subs(get2json2$results[[1]]$`2011`)
UIdata2010 = get_subs(get2json2$results[[1]]$`2010`)
UIdata2009 = get_subs(get2json2$results[[1]]$`2009`)
UIdata2008 = get_subs(get2json2$results[[1]]$`2008`)
UIdata2007 = get_subs(get2json2$results[[1]]$`2007`)
UIdata2006 = get_subs(get2json2$results[[1]]$`2006`)
UIdata2005 = get_subs(get2json2$results[[1]]$`2005`)
UIdata2004 = get_subs(get2json2$results[[1]]$`2004`)
UIdata2003 = get_subs(get2json2$results[[1]]$`2003`)
UIdata2002 = get_subs(get2json2$results[[1]]$`2002`)
UIdata2001 = get_subs(get2json2$results[[1]]$`2001`)
UIdata2000 = get_subs(get2json2$results[[1]]$`2000`)
UIdata1999 = get_subs(get2json2$results[[1]]$`1999`)
UIdata1998 = get_subs(get2json2$results[[1]]$`1998`)
UIdata1997 = get_subs(get2json2$results[[1]]$`1997`)
UIdata1996 = get_subs(get2json2$results[[1]]$`1996`)
#join all of the dataframes from each year into one full dataframe by subtopic
UIcompletionData = UIjoin_rename(1)
UIstudentsData = UIjoin_rename(2)
UIadmissionData = UIjoin_rename(3)
UIacademicsData = UIjoin_rename(4)
UIaidData = UIjoin_rename(5)
UIrepaymentData = UIjoin_rename(6)
UIearningsData = UIjoin_rename(7)
UIcostData = UIjoin_rename(8)
ISUacademicsData
```




## Two Segments.
1) Academic/Students
  -completion
  -students
  -admissions
  -academics
  
2) Financials
  -aid
  -repayments
  -earnings
  -cost

--------DANNY---------
```{r}
#comparison between the count of ISU and UI 4 year completion students.
ISUvsUIcompl = inner_join(ISUcompletionData, UIcompletionData, by = "rn")
ISUvsUIcompl = ISUvsUIcompl %>% select(rn, `4_yr_completion.overall.x`, `4_yr_completion.female_students.x`, `4_yr_completion.male_students.x`, `4_yr_completion.overall.y`, `4_yr_completion.female_students.y`, `4_yr_completion.male_students.y`)
ISUvsUIcompl = ISUvsUIcompl[complete.cases(ISUvsUIcompl), ]
ggplot(ISUvsUIcompl) + 
  geom_line(aes(x = rn, y = `4_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_line(aes(x = rn, y = `4_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_line(aes(x = rn, y = `4_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_line(aes(x = rn, y = `4_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_line(aes(x = rn, y = `4_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_line(aes(x = rn, y = `4_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `4_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_point(aes(x = rn, y = `4_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_point(aes(x = rn, y = `4_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_point(aes(x = rn, y = `4_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `4_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_point(aes(x = rn, y = `4_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE"))
```

```{r}
#comparison between the count of ISU and UI 6 year completion students.
ISUvsUIcompl2 = inner_join(ISUcompletionData, UIcompletionData, by = "rn")
ISUvsUIcompl2 = ISUvsUIcompl2 %>% select(rn, `6_yr_completion.overall.x`, `6_yr_completion.female_students.x`, `6_yr_completion.male_students.x`, `6_yr_completion.overall.y`, `6_yr_completion.female_students.y`, `6_yr_completion.male_students.y`)
ISUvsUIcompl2 = ISUvsUIcompl2[complete.cases(ISUvsUIcompl2), ]
ggplot(ISUvsUIcompl2) + 
  geom_line(aes(x = rn, y = `6_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_line(aes(x = rn, y = `6_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_line(aes(x = rn, y = `6_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_line(aes(x = rn, y = `6_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_line(aes(x = rn, y = `6_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_line(aes(x = rn, y = `6_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `6_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_point(aes(x = rn, y = `6_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_point(aes(x = rn, y = `6_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_point(aes(x = rn, y = `6_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `6_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_point(aes(x = rn, y = `6_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE"))
```

```{r}
#comparison between the count of ISU and UI 8 year completion students.
ISUvsUIcompl3 = inner_join(ISUcompletionData, UIcompletionData, by = "rn")
ISUvsUIcompl3 = ISUvsUIcompl3 %>% select(rn, `8_yr_completion.overall.x`, `8_yr_completion.female_students.x`, `8_yr_completion.male_students.x`, `8_yr_completion.overall.y`, `8_yr_completion.female_students.y`, `8_yr_completion.male_students.y`)
ISUvsUIcompl3 = ISUvsUIcompl3[complete.cases(ISUvsUIcompl3), ]
ggplot(ISUvsUIcompl3) + 
  geom_line(aes(x = rn, y = `8_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_line(aes(x = rn, y = `8_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_line(aes(x = rn, y = `8_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_line(aes(x = rn, y = `8_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_line(aes(x = rn, y = `8_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_line(aes(x = rn, y = `8_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `8_yr_completion.overall.x`, group = 1, color = "ISU")) + 
  geom_point(aes(x = rn, y = `8_yr_completion.overall.y`, group = 1, color = "UI")) +
  geom_point(aes(x = rn, y = `8_yr_completion.female_students.x`, group = 1, color = "ISU", linetype = "FEMALE")) +
  geom_point(aes(x = rn, y = `8_yr_completion.male_students.x`, group = 1, color = "ISU", linetype = "MALE")) +
  geom_point(aes(x = rn, y = `8_yr_completion.female_students.y`, group = 1, color = "UI", linetype = "FEMALE")) + 
  geom_point(aes(x = rn, y = `8_yr_completion.male_students.y`, group = 1, color = "UI", linetype = "MALE"))
```

```{r}
#comparison of average overall sat scores between ISU and UI.
ISUvsUIadmis = inner_join(ISUadmissionData, UIadmissionData, by = "rn")
ISUvsUIadmis = ISUvsUIadmis %>% select(rn, `sat_scores.average.overall.x`, `sat_scores.average.overall.y`)
ISUvsUIadmis = ISUvsUIadmis[complete.cases(ISUvsUIadmis), ]
ggplot(ISUvsUIadmis) + 
  geom_line(aes(x = rn, y = `sat_scores.average.overall.x`, group = 1, color = "ISU", linetype = "SAT")) +
  geom_line(aes(x = rn, y = `sat_scores.average.overall.y`, group = 1, color = "UI", linetype = "SAT")) +
  geom_point(aes(x = rn, y = `sat_scores.average.overall.x`, group = 1, color = "ISU", linetype = "SAT")) + 
  geom_point(aes(x = rn, y = `sat_scores.average.overall.y`, group = 1, color = "UI", linetype = "SAT")) 
```  

```{r}
#comparison of overall admission rates between ISU and UI.
ISUvsUIadmis2 = inner_join(ISUadmissionData, UIadmissionData, by = "rn")
ISUvsUIadmis2 = ISUvsUIadmis2 %>% select(rn, `admission_rate.overall.x`, `admission_rate.overall.y`)
ISUvsUIadmis2 = ISUvsUIadmis2[complete.cases(ISUvsUIadmis2), ]
ggplot(ISUvsUIadmis2) +
  geom_line(aes(x = rn, y = `admission_rate.overall.x`, group = 1, color = "ISU", linetype = "ADMIS")) +
  geom_line(aes(x = rn, y = `admission_rate.overall.y`, group = 1, color = "UI", linetype = "ADMIS")) +
  geom_point(aes(x = rn, y = `admission_rate.overall.x`, group = 1, color = "ISU", linetype = "ADMIS")) +
  geom_point(aes(x = rn, y = `admission_rate.overall.y`, group = 1, color = "UI", linetype = "ADMIS"))
```
--------DANNY---------

---------LIM----------
```{r}


```
---------LIM----------

---------SAM-----------
```{r}
ISUvsUIcost = inner_join(ISUcostData,UIcostData,by="rn") 
ISUvsUIcost = ISUvsUIcost %>% select(rn,tuition.out_of_state.x,tuition.in_state.x,tuition.out_of_state.y,tuition.in_state.y)
ISUvsUIcost = type.convert(ISUvsUIcost)
ggplot(ISUvsUIcost) + 
geom_line(aes(x=rn,y=tuition.out_of_state.x,group = 1,color="ISU",linetype="Out of State")) + geom_line(aes(x=rn,y=tuition.out_of_state.y,group = 1,color="UI",linetype="Out of State")) + geom_line(aes(x=rn,y=tuition.in_state.y,group = 1,color="UI",linetype="In State")) + geom_line(aes(x=rn,y=tuition.in_state.x,group = 1,color="ISU",linetype="In State")) +
geom_point(aes(x=rn,y=tuition.out_of_state.x,group = 1,color="ISU")) + geom_point(aes(x=rn,y=tuition.out_of_state.y,group = 1,color="UI")) + geom_point(aes(x=rn,y=tuition.in_state.y,group = 1,color="UI")) + 
geom_point(aes(x=rn,y=tuition.in_state.x,group = 1,color="ISU"))
```



```{r}
ISUvsUIearnings = inner_join(ISUearningsData,UIearningsData,by="rn")
ISUvsUIearnings = ISUvsUIearnings %>% select(rn,`10_yrs_after_entry.working_not_enrolled.mean_earnings.x`,`10_yrs_after_entry.mean_earnings.female_students.x`,`10_yrs_after_entry.mean_earnings.male_students.x`,`10_yrs_after_entry.working_not_enrolled.mean_earnings.y`,`10_yrs_after_entry.mean_earnings.female_students.y`,`10_yrs_after_entry.mean_earnings.male_students.y`)
ISUvsUIearnings = ISUvsUIearnings[complete.cases(ISUvsUIearnings), ]
ggplot(ISUvsUIearnings) + 
geom_line(aes(x=rn,y=`10_yrs_after_entry.working_not_enrolled.mean_earnings.x`,group = 1,color="MEANISU")) + 
geom_line(aes(x=rn,y=`10_yrs_after_entry.working_not_enrolled.mean_earnings.y`,group = 1,color="MEANUI")) +
geom_line(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.female_students.x`,group = 1,color="ISU",linetype="FEMALE")) +
geom_line(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.male_students.x`,group = 1,color="ISU",linetype="MALE")) +
geom_line(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.female_students.y`,group = 1,color="UI",linetype="FEMALE")) + 
geom_line(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.male_students.y`,group = 1,color="UI",linetype="MALE")) +
geom_point(aes(x=rn,y=`10_yrs_after_entry.working_not_enrolled.mean_earnings.x`,group = 1,color="MEANISU")) + 
geom_point(aes(x=rn,y=`10_yrs_after_entry.working_not_enrolled.mean_earnings.y`,group = 1,color="MEANUI")) +
geom_point(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.female_students.x`,group = 1,color="ISU",linetype="FEMALE")) +
geom_point(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.male_students.x`,group = 1,color="ISU",linetype="MALE")) +
geom_point(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.female_students.y`,group = 1,color="UI",linetype="FEMALE")) + 
geom_point(aes(x=rn,y=`10_yrs_after_entry.mean_earnings.male_students.y`,group = 1,color="UI",linetype="MALE")) 
```



```{r}
ISUaidvisData = ISUaidData %>% select(rn,median_debt.no_pell_grant,median_debt.pell_grant,median_debt.completers.overall,median_debt.noncompleters)
UIaidvisData = UIaidData %>% select(rn,median_debt.no_pell_grant,median_debt.pell_grant,median_debt.completers.overall,median_debt.noncompleters)
ISUvsUIaid = inner_join(ISUaidvisData,UIaidvisData,by='rn')
ISUvsUIaid
ggplot(ISUvsUIaid, aes(x=rn)) + 
geom_line(aes(y=median_debt.no_pell_grant.x,group=1,color="ISU",linetype="No Pell"))+
geom_line(aes(y=median_debt.no_pell_grant.y,group=1,color="UI",linetype="No Pell"))+
geom_line(aes(y=median_debt.pell_grant.x,group=1,color="ISU",linetype="Pell"))+
geom_line(aes(y=median_debt.pell_grant.y,group=1,color="UI",linetype="Pell"))
```


```{r}
data1 = ISUaidData %>% select(rn,median_debt.completers.overall,median_debt.noncompleters)
data2 = UIaidData %>% select(rn,median_debt.completers.overall,median_debt.noncompleters)
ISUvsUIcompleters = inner_join(data1,data2,by='rn')
ISUvsUIcompleters
ggplot(ISUvsUIcompleters,aes(x=rn))+
geom_line(aes(y=median_debt.completers.overall.x,group=1,color="ISU",linetype="completers"))+
geom_line(aes(y=median_debt.completers.overall.y,group=1,color="UI",linetype="completers"))+
geom_line(aes(y=median_debt.noncompleters.x,group=1,color="ISU",linetype="noncompleters"))+
geom_line(aes(y=median_debt.noncompleters.y,group=1,color="UI",linetype="noncompleters"))
```
---------SAM-----------