---
title: "Proposal"
author: "Sam Shifflett"
date: "4/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Team Member Names:
Sam Shifflett (Coodinator)
Danny Nguyen
Lim Guang

We are extracting data from the Department of Education
We are specifically targeting the College Score Card Data through API calls to their Servers
Overview
We are able to construct different dataframes off of the JSON repsonse that covers topics:
  1) completion stats
  2) earnings from students reports
  3) student body demographics
  4) admission stats
  5) aid overviews
  6) repayment plans and stats
We are able to filter the data based on year from 1996 to 2016

Link:
This is the api call to return the JSON response(place in browser to see JSON):
https://api.data.gov/ed/collegescorecard/v1/schools.json?api_key=KYthZktaAwB5CMGp9Keyl3raXpb6CS43CaMhbLkr&school.name=Iowa%20State%20University

This will return a list of statistics based on the year and the subsetted topics

We hope to draw insights of the changes within certain categories of each year.
Possible examples can be:
  1) How have the default rates on certain loan repayment plans changed over the years?
  2) What are the student earnings from graduates and how have they changed?
  3) How many students are using aid compared to the whole student body?
  etc.

There is much more data that we can collect, but to start off we are keeping it simple with student information.



